### ISSUE TITLE
Add support for laravel 7.x

### ISSUE THREAD

**Issue by didix16** [mailjet/laravel-mailjet#29]
Hello guys.
I'm using this fabulous library for handling emails inside my laravel project. Now my company needs to update Laravel to 7.x but this package does not support it since the laravel/tinker requirment does not match...

Laravel 7.x needs laravel/tinker at ^2.0 and this package is at ~1.0.

Could you update the requirement to be compatible with Laravel 7.x ?

Thank you so much.

**Comment by TheDoctor0** [comment]
There is a PR (#27) open for more than a month now, but still no response or action from Mailjet guys.

**Comment by didix16** [comment]
I hope then they can do something soon. Meanwhile, I used your forked branch. It worked like a charm :+1: 

Thanks @TheDoctor0

**Comment by ramon-noordeloos** [comment]
> There is a PR (#27) open for more than a month now, but still no response or action from Mailjet guys.

@TheDoctor0  when using your forked branch I am getting a "Unsupported mail transport [mailjet]" exception when using the Laravel mail feature.  Any idea how to solve this?  

It's disappointing that the Mailjet guys don't seem to take Laravel seriously anymore... :(

**Comment by TheDoctor0** [comment]
@ramon-noordeloos, looking at a source code of [MailManager](https://github.com/laravel/framework/blob/master/src/Illuminate/Mail/MailManager.php#L110), it seems that there is some problem with your configuration.

**Comment by ramon-noordeloos** [comment]
> @ramon-noordeloos, looking at a source code of [MailManager](https://github.com/laravel/framework/blob/master/src/Illuminate/Mail/MailManager.php#L110), it seems that there is some problem with your configuration.

@TheDoctor0, I first thought this was also the problem, but I am following exact all configuration instructions for the Mailjet Laravel package as descripted in the README.md file. But maybe I am missing something. The strange thing is that on the latest version of Laravel 6 everything is working as a charm. When upgrading to Laravel 7 I get this error. I also tried a fresh install of Laravel 7 but the same error occurs. 

I also tried to the old and new mail configuration format in Laravel but the same error.

In the mail.php file I have this:

'default' => env('MAIL_MAILER', 'smtp'), //which is mailjet 

and I extended the mailers array with:

mailjet => [
            'transport' => mailjet,
        ]

**Comment by TheDoctor0** [comment]
@ramon-noordeloos, I investigated the issue and you are absolutely right. 
This package cannot be used with Laravel 7, because under the hood there is new mail driver manager and method used here to register transport driver has been dropped.

I decided to create my own package as next PR here seems like a waste of time. 
Support for Laravel 7 has been added: [laravel-mailjet-driver](https://github.com/TheDoctor0/laravel-mailjet-driver).

**Comment by limonte** [comment]
AMAZING work @TheDoctor0  :clap: 

Thank you so much!

**Comment by ramon-noordeloos** [comment]
> @ramon-noordeloos, I investigated the issue and you are absolutely right.
> This package cannot be used with Laravel 7, because under the hood there is new mail driver manager and method used here to register transport driver has been dropped.
> 
> I decided to create my own package as next PR here seems like a waste of time.
> Support for Laravel 7 has been added: [laravel-mailjet-driver](https://github.com/TheDoctor0/laravel-mailjet-driver).

You made my day @TheDoctor0 !!!! Many thank for your quick respons and help. Really Amazing. We can finally upgrade to Laravel 7 🚀

**Comment by lalmat** [comment]
Thank you @TheDoctor0 !

**Comment by Greedito** [comment]
I've been struggling with laravel-mailjet package and my Laravel 7 version, then I found your work @TheDoctor0, and it works like a charm ! Thank's a lot !

**Comment by didix16** [comment]
Thanks @TheDoctor0. I was getting "Unsupported mail transport" exception this days... Finally I removed the old mailjet package and using yours and works like a charm!. Hope can be keep up to day :)

Thanks once more.

**Comment by camachogfelipe** [comment]
Hi @TheDoctor0

How do I integrate this library with Laravel Auth? It gives me an **Offset 0** error in _MessagePayloadV31.php: 103_

I already set the constant **MAIL_FROM_ADDRESS** and it is not fixed

**Comment by TheDoctor0** [comment]
@camachogfelipe, if you are getting error in _MessagePayloadV31.php_ it's probably not related to the driver package at all.
This file is from **maljet/mailjet-swiftmailer** package, so report an issue here: https://github.com/mailjet/MailjetSwiftMailer.

**Comment by kikiluawo** [comment]
@TheDoctor0 I have followed the step by step here, but when I registered for the website wi account that I created, I did not receive the verification link in the email. my .env settings are like this 
![env](https://user-images.githubusercontent.com/66511085/92068762-fa35d080-edd1-11ea-966a-8f046d53db34.jpg)

**Comment by TheDoctor0** [comment]
@kikiluawo, it's a really bad idea to post a screenshot with your API key and secret!

About your problem, make sure that mail sender address in config/mail.php is an authorized sender on your Mailjet account.

**Comment by iKlsR** [comment]
I just moved my entire email stack to mailjet and seeing this thread and running into this issue... not very hopeful but thanks @TheDoctor0

**Comment by ngarnier** [comment]
@kikiluawo I deleted your comment as it included your API keys. 

As you can see from PR #32, we're working to add support for the most recent versions of Laravel.

**Comment by uavn** [comment]
Should work now

**Comment by i-fail** [comment]
Having the same error.

I traced it down to this line in vendor\laravel\framework\src\Illuminate\Mail\**MailManager.php**

` $transport = $config['transport'] ?? $this->app['config']['mail.driver'];`

MailJet's **$config** (which is passed down to here correctly) doesn't have the 'transport' field. And **$this->app['config']** doesn't have the **'mail.driver'** field.

**Comment by i-fail** [comment]
Still getting Unsupported mail transport [mailjet]

**Comment by dan-scott-dev** [comment]
Still getting Unsupported mail transport [mailjet]

Laravel 8.

`MAIL_MAILER=mailjet` in my .env

And this in config/mail.php in the 'mailers' array:

```
'mailjet' => [
            'transport' => 'mailjet',
        ],
```
